trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install npm dependencies'

- script: |
    npm run build
  displayName: 'Run build'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: NodeApp
  displayName: 'Publish Artifact'